import { IClass } from '../models/class.interface';
import { ILesson } from '../models/lessons.interface';
import { IProgress } from '../models/progress.interface';
import { IUser } from '../models/user.interface';

// export const bbLessonsInit: ILesson[] = [
//     {
//         id: 'bblesson01',
//         name: 'Sealed Book and Revelation',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 1',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '1',
//     },
//     {
//         id: 'bblesson02',
//         name: 'Seed and Harvest (Sign of Second Coming)',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 2',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '2',
//     },
//     {
//         id: 'bblesson03',
//         name: 'How to read Prophecy (Prophecy and Secrets of the Kingdom of Heaven in Parable) ',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 3',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '3',
//     },
//     {
//         id: 'bblesson04',
//         name: 'Introduction to Revelation',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 4',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '4',
//     },
//     {
//         id: 'bblesson05',
//         name: 'Moses’s Tabernacle & Copy and Shadow/Reality',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 5',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '5',
//     },
//     {
//         id: 'bblesson06',
//         name: 'Elementary teaching and teaching of righteousness for the mature',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 6',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '6',
//     },
//     {
//         id: 'bblesson07',
//         name: 'God’s covenants (OT and NT)',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 7',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '7',
//     },
//     {
//         id: 'bblesson08',
//         name: 'God’s will and purpose (6,000 years of God’s work and history)',
//         description: '',
//         category: 'bb',
//         path: 'BB Lesson 8',
//         language: 'English',
//         instructor: 'Thomas',
//         lessonNo: '8',
//     },
// ];

export const progressData: IProgress = {
    id: '',
    email: '',
    classId: '',
    userId: '',
    categoryProgress: [
        {
            categoryName: 'BB',
            locked: false,
            progress: '0',
            lessons: [
                {
                    id: 'bblesson01',
                    name: 'Sealed Book and Revelation',
                    lessonNo: '1',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: false,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson02',
                    name: 'Seed and Harvest (Sign of Second Coming)',
                    lessonNo: '2',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson03',
                    name: 'How to read Prophecy (Prophecy and Secrets of the Kingdom of Heaven in Parable)',
                    lessonNo: '3',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson04',
                    name: 'Introduction to Revelation',
                    lessonNo: '4',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson05',
                    name: 'Moses’s Tabernacle & Copy and Shadow/Reality',
                    lessonNo: '5',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson06',
                    name: 'Elementary teaching and teaching of righteousness for the mature',
                    lessonNo: '6',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson07',
                    name: 'God’s covenants (OT and NT)',
                    lessonNo: '7',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
                {
                    id: 'bblesson08',
                    name: 'God’s will and purpose (6,000 years of God’s work and history)',
                    lessonNo: '8',
                    watchDuration: 0,
                    progress: '0',
                    completed: false,
                    locked: true,
                    startDate: null,
                    completedDate: null,
                    postQuizId: null,
                    quizAnswers: null,
                },
            ],
        },
        {
            categoryName: 'Introductory',
            progress: '0',
            locked: true,
            lessons: [],
        },
        {
            categoryName: 'Intermediate',
            progress: '0',
            locked: true,
            lessons: [],
        },
        {
            categoryName: 'Advanced',
            progress: '0',
            locked: true,
            lessons: [],
        },
    ],
};

export const seedUser: IUser[] = [
    {
        id: 'usr-001',
        role: 'student',
        name: 'Alice Johnson',
        classId: 'cls-101A',
        networker: 'John Doe',
        instructor: 'Jane Smith',
        language: 'English',
        userDetails: {
            age: '25',
            dob: '1999-03-15',
            phone: '+1-555-123-4567',
            religion: 'Christian',
            occupation: 'Software Engineer',
            gender: 'Female',
            marital: 'Single',
            whyApply: 'To improve my skills',
            studying: 'Web Development',
        },
        email: 'alice.johnson@example.com',
    },
    {
        id: 'usr-002',
        role: 'student',
        name: 'Carlos Hernandez',
        classId: 'cls-102B',
        networker: 'Maria Garcia',
        instructor: 'David Lee',
        language: 'Spanish',
        userDetails: {
            age: '32',
            dob: '1992-08-22',
            phone: '+1-555-987-6543',
            religion: 'Agnostic',
            occupation: 'Data Analyst',
            gender: 'Male',
            marital: 'Married',
            whyApply: 'Career advancement',
            studying: 'Data Science',
        },
        email: 'carlos.hernandez@example.com',
    },
    {
        id: 'usr-003',
        role: 'student',
        name: 'Priya Patel',
        classId: 'cls-101A',
        networker: 'John Doe',
        instructor: 'Jane Smith',
        language: 'Hindi',
        userDetails: {
            age: '28',
            dob: '1996-11-05',
            phone: '+91-9876543210',
            religion: 'Hindu',
            occupation: 'Marketing Manager',
            gender: 'Female',
            marital: 'Other',
            whyApply: 'Personal growth',
            studying: 'Digital Marketing',
        },
        email: 'priya.patel@example.com',
    },
];

export const classData: IClass[] = [
    {
        id: '',
        classId: 'cls_12345',
        instructor: 'Thomas',
        networker: 'John Dilip',
        language: 'English',
        startDate: '',
        endDate: '',
        students: [
            { studentId: 'std_001', name: 'Alice Johnson' },
            { studentId: 'std_002', name: 'Bob Williams' },
            { studentId: 'std_003', name: 'Eva Martinez' },
        ],
    },
    {
        id: '',
        classId: 'cls_54321',
        instructor: 'Theo',
        networker: 'Maria',
        language: 'Tamil',
        startDate: '',
        endDate: '',
        students: [
            { studentId: 'std_004', name: 'David Lee' },
            { studentId: 'std_005', name: 'Sofia Nguyen' },
        ],
    },
    {
        id: '',
        classId: 'FRN303-C',
        instructor: 'Jessie',
        networker: 'Ezra',
        language: 'English',
        startDate: '',
        endDate: '',
        students: [
            { studentId: 'std_006', name: 'Liam Patel' },
            { studentId: 'std_007', name: 'Olivia Kim' },
            { studentId: 'std_008', name: 'Noah Brown' },
            { studentId: 'std_009', name: 'Emma Wilson' },
        ],
    },
    // Add more classes as needed...
];
